data:
  class_map: {"benign": 0, "malignant": 1}
  filename_col: "image_name"
  label_col: "benign_malignant"

model:
  image_size: 512
  patch_size: 64
  embed_dim: 128
  num_heads: 3
  num_classes: 2
  model_name: "trained_model"
  quantized_model_name: "quantized_model"
  deployable_model_name: "deployable_model"
  num_workers: 8
  