data:
  class_map: {"benign": 0, "malignant": 1}
  filename_col: "image_name"
  label_col: "benign_malignant"

training:
  batch_size: 32
  epochs: 3
  seed: 42
  limit_train_batches: 0.2
  model_path: "trained_model.pt"

model:
  image_size: 512
  patch_size: 64
  embed_dim: 128
  num_heads: 3
  num_classes: 2
  lr: 1e-3