data:
  class_map: {"benign": 0, "malignant": 1}
  filename_col: "image_name"
  label_col: "benign_malignant"

training:
  batch_size: 32
  epochs: 1
  seed: 42
  limit_train_batches: 0.1
  model_path: "trained_model.pt"
  quantized_model_path: "quantized_model.pt"
  deployable_model_path: "deployable_model.pt"
  num_workers: 8

model:
  image_size: 512
  patch_size: 64
  embed_dim: 128
  num_heads: 3
  num_classes: 2
  lr: 1e-3